# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fa6daf8bb4389ff9b525bbf470b1e45aa64696ef4aad0e8b233d0ff454178c77d6dc336a9ec4c64368e2dca45bc7369d57e3bc608e95b1059ea4cfdc89343c2

test:
  secret_key_base: 9a3d39620dac71aabaa029ec8a3c3ba7c5b341abe31cd111c435942ba6c4de06c64998824d57d02556d19dd1ca83ca6ae42d13c6e3362324956d1e347d9a200c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
